### ISSUE TITLE
update Remove-AzSentinelAlertRule to accept value from pipeline

### ISSUE THREAD

**Issue by pkhabazi** [wortell/AZSentinel#10]
**Remove-AzSentinelAlertRule**
I was thinking I could do the following Example, but instead I received errors, Maybe I am using it wrong.
![image](https://user-images.githubusercontent.com/9781801/64494794-8978d880-d291-11e9-9419-9ff341bca60b.png)
I did see RuleName accepts pipeline input in the helpfiles and it says (ByValue).
Perhaps I am doing this wrong, I just expected it work like in my example. 
I have seen a similar way of working in other modules. 

Confirm works perfect, great choice of options. 

I do think it always should prompt for deletion and -Force will ovveride this behaviour.

_Originally posted by @MauRiEEZZZ in https://github.com/wortell/AZSentinel/pull/9#issuecomment-529244077_

**Comment by pkhabazi** [comment]
You can do this by executing the following code:
```PowerShell
$(Get-AzSentinelAlertRule -WorkspaceName pkm02 | where {$_.displayname -like "Rule09*"}).displayName | Remove-AzSentinelAlertRule -WorkspaceName pkm02
```
![image](https://user-images.githubusercontent.com/20944041/64512895-ac35dc00-d2e7-11e9-8242-6f76c9ebaad4.png)

**Comment by pkhabazi** [comment]
@MauRiEEZZZ I think we can close this issue?

**Comment by MauRiEEZZZ** [comment]
Is it an idea I create a second constructor to allow the AlertRule object from pipeline in addition to the array of strings?

Groeten,
Maurice
________________________________
Van: Pouyan Khabazi <notifications@github.com>
Verzonden: Tuesday, September 10, 2019 10:06:22 AM
Aan: wortell/AZSentinel <AZSentinel@noreply.github.com>
CC: Maurice MJ de Jong <maurieezzz@hotmail.com>; Mention <mention@noreply.github.com>
Onderwerp: Re: [wortell/AZSentinel] update Remove-AzSentinelAlertRule to accept value from pipeline (#10)


@MauRiEEZZZ<https://github.com/MauRiEEZZZ> I think we can close this issue?

**Comment by pkhabazi** [comment]
Closing this issue
