### ISSUE TITLE
Feature Request: Abilitiy to save a scheduled rule into a json file that is compatible with AzSentinel schema

### ISSUE THREAD

**Issue by Cyb3r-Monk** [wortell/AZSentinel#109]
The schema requires the scheduled rule to be enclosed in  `{  "Scheduled": [ ... ] }`. when using Get-AzSentinelAlertRule, it is possible to convert the content into JSON but the  `{  "Scheduled": [ ... ] }` is missing. It would be nice to have an option for downloading a scheduled rule in a JSON format that is compatible to the AzSentinel schema. In addition, if the function can remove some attributes (like etag, id, etc.) it would make it easy to pull a rule from an environment and push it to another one without modifying the json content.

**Comment by pkhabazi** [comment]
Thanks for your feedback @Cyb3r-Monk! I am currently working on a export function, will try to include it in the next release.

**Comment by javiersoriano** [comment]
+1, this would be great!
