### ISSUE TITLE
Please upload to PowerShell Gallery

### ISSUE THREAD

**Issue by anirudhgarg** [wortell/AZSentinel#11]
Please upload this module to PowerShell Gallery, then this can be trivially used in Azure Functions.

**Comment by pkhabazi** [comment]
@anirudhgarg  thanks for your feedback. We are currently working on a build pipeline which will release the module to the PowerShell Gallery. Will be done in coming days hopefully

**Comment by pkhabazi** [comment]
version 0.6.0 is available in PowerShell Gallery
https://www.powershellgallery.com/packages/AzSentinel/0.6.0

**Comment by anirudhgarg** [comment]
Thanks @pkhabazi for doing this. Now we can use this in Azure Functions easily.
