### ISSUE TITLE
"requiredDataConnectors" not populating

### ISSUE THREAD

**Issue by Edi-Lahav** [wortell/AZSentinel#113]
# Summary of the new feature/enhancement
When using the Get-AzSentinelAlertRuleTemplates the requiredDataConnectors output parameter. 
It can be useful also to add it as an Input parameter to filter alert templates by the Data Connectors.

# Proposed technical implementation details (optional)
When trying the Alert Rule Template GET - the response includes this output parameter. It'll be great to have in the response.

**Comment by pkhabazi** [comment]
hi @Edi-Lahav, thanks for the feedback. the property is there but currently a little bit hidden :p I am working to update the output.

For now you can access the requiredDataConnectors by running the following, the below example will return the displayname and requiredDataConnectors for all the templaterules:
```PowerShell
Get-AzSentinelAlertRuleTemplates -WorkspaceName  | select {$_.properties.requiredDataConnectors.connectorId}, {$_.properties.displayName}
```

**Comment by pkhabazi** [comment]
example of new output:
![image](https://user-images.githubusercontent.com/20944041/96580442-92333f00-12d8-11eb-8a71-38ccfc0e5c2c.png)
