### ISSUE TITLE
Bug Report Install-Package  The following commands are already available on this system:'Login-AzAccount'...

### ISSUE THREAD

**Issue by PatrickGallucci** [wortell/AZSentinel#115]
# Environment

```none
Windows build number: [run "ver" at a command prompt]
PowerShell version (if applicable):

Any other software?
```
Current Azure Az modules.

# Steps to reproduce
Install-Module AzSentinel -Scope CurrentUser -Force  

# Expected behavior

# Actual behavior

Install-Module AzSentinel -Scope CurrentUser -Force                                                                                                                        PackageManagement\Install-Package : The following commands are already available on this system:'Login-AzAccount,Logout-AzAccount,Resolve-Error,Send-Feedback'. This module 'Az.Accounts' may override
the existing commands. If you still want to install this module 'Az.Accounts', use -AllowClobber parameter.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\2.2.5\PSModule.psm1:9711 char:34
+ ... talledPackages = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Microsoft.Power....InstallPackage:InstallPackage) [Install-Package], Exception
    + FullyQualifiedErrorId : CommandAlreadyAvailable,Validate-ModuleCommandAlreadyAvailable,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage

**Comment by pkhabazi** [comment]
hi @PatrickGallucci I think you have already an "older" version of Az.Accounts installed. Please try  updating Az.Accounts by running (I think you need to run it  with "run as administrator"):
```PowerShell
Update-Module Az.Accounts -Force
```
or try by installing it with Allowclobber
```PowerShell
Install-Module AzSentinel -Scope CurrentUser -Force -AllowClobber
```

**Comment by pkhabazi** [comment]
@PatrickGallucci can we close this issue or do you need more support?

**Comment by pkhabazi** [comment]
no answer received, closing issue
