### ISSUE TITLE
Import-AzSentinelAlertRule failes with 400 status code if the query isn't one-liner

### ISSUE THREAD

**Issue by cac0ns3c** [wortell/AZSentinel#124]
**In raising this issue, I confirm the following:** 

- [v] I have read and understood the [contributors guide](.\CONTRIBUTING.md).
- [v] The issue I am reporting can be *replicated*.
- [v] The issue I am reporting isn't a duplicate (see [FAQs](##/wiki/FAQs), [closed issues](https://github.com/wortell/AZSentinel/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed), and [open issues](https://github.com/wortell/AZSentinel/issues?q=is%3Aissue+is%3Aopen)).

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behaviour:**

Deploy a rule which isn't one-liner

**Actual behaviour:**

when creating a rule which is not one-liner i get 400 status code, when i create it as one-liner everything works

**Steps to reproduce:**

just deploy with the query
SecurityEvents
| where EventID == 4688

**Troubleshooting undertaken, and/or other relevant information:**

**Comment by pkhabazi** [comment]
hi @cac0ns3c I think the issue is more related in the query, the table name should be "SecurityEvent" instead of "SecurityEvent**s**"

try the below example:
```JSON
{
  "Scheduled": [
    {
      "displayName": "AlertRule01",
      "description": "",
      "severity": "Medium",
      "enabled": true,
      "query": "SecurityEvent
      | where EventID == \"4699\" ",
      "queryFrequency": "5H",
      "queryPeriod": "6H",
      "triggerOperator": "GreaterThan",
      "triggerThreshold": 5,
      "suppressionDuration": "6H",
      "suppressionEnabled": false,
      "tactics": [
        "Persistence",
        "LateralMovement",
        "Collection"
      ],
      "playbookName": "",
      "aggregationKind": "SingleAlert",
      "createIncident": true,
      "groupingConfiguration": {
        "enabled": false,
        "reopenClosedIncident": false,
        "lookbackDuration": "PT5H",
        "entitiesMatchingMethod": "All",
        "groupByEntities": [
          "Account",
          "Ip",
          "Host",
          "Url"
        ]
      }
    }
  ]
}
```

**Comment by cac0ns3c** [comment]
Sorry, that was a mistake, that was just an example

let's say i have this query:
`let endtime = 1d;
  let starttime = 8d;
  // The threshold below excludes matching on RDP connection computer counts of 5 or more by a given account and IP in a given day.  Change the threshold as needed.
  let threshold = 5;
  SecurityEvent
  | where TimeGenerated >= ago(endtime) 
  | where EventID == 4624 and LogonType == 10
  // Labeling the first RDP connection time, computer and ip
  | extend FirstHop = TimeGenerated, FirstComputer = toupper(Computer), FirstIPAddress = IpAddress, Account = tolower(Account)  
  | join kind=inner (
  SecurityEvent
  | where TimeGenerated >= ago(endtime) 
  | where EventID == 4624 and LogonType == 10 // checks for something
  // Labeling the second RDP connection time, computer and ip
  | extend SecondHop = TimeGenerated, SecondComputer = toupper(Computer), SecondIPAddress = IpAddress, Account = tolower(Account)
  ) on Account
  // Make sure that the first connection is after the second connection --> SecondHop > FirstHop
  // Then identify only RDP to another computer from within the first RDP connection by only choosing matches where the Computer names do not match --> FirstComputer != SecondComputer
  // Then make sure the IPAddresses do not match by excluding connections from the same computers with first hop RDP connections to multiple computers --> FirstIPAddress != SecondIPAddress
  | where FirstComputer != SecondComputer and FirstIPAddress != SecondIPAddress and SecondHop > FirstHop
  // where the second hop occurs within 30 minutes of the first hop
  | where SecondHop <= FirstHop+30m
  | distinct Account, FirstHop, FirstComputer, FirstIPAddress, SecondHop, SecondComputer, SecondIPAddress, AccountType, Activity, LogonTypeName, ProcessName
  // use left anti to exclude anything from the previous 7 days where the Account and IP has connected 5 or more computers.
  | join kind=leftanti (
  SecurityEvent
  | where TimeGenerated >= ago(starttime) and TimeGenerated < ago(endtime) 
  | where EventID == 4624 and LogonType == 10
  | summarize makeset(Computer), ComputerCount = dcount(Computer) by bin(TimeGenerated, 1d), Account = tolower(Account), IpAddress
  // Connection count to computer by same account and IP to exclude counts of 5 or more on a given day
  | where ComputerCount >= threshold
  | mvexpand set_Computer
  | extend Computer = toupper(set_Computer)
  ) on Account, $left.SecondComputer == $right.Computer, $left.SecondIPAddress == $right.IpAddress
  | summarize FirstHopFirstSeen = min(FirstHop), FirstHopLastSeen = max(FirstHop) by Account, FirstComputer, FirstIPAddress, SecondHop, SecondComputer, 
  SecondIPAddress, AccountType, Activity, LogonTypeName, ProcessName
  | extend timestamp = FirstHopFirstSeen, AccountCustomEntity = Account, HostCustomEntity = FirstComputer, IPCustomEntity = FirstIPAddress`

and i don't want it to be in one-line.

another bug that i found that caused because the one line see my comment on the 3rd line ( // checks for something )
all the code after that will be commented
