### ISSUE TITLE
Access token expiration logic

### ISSUE THREAD

**Issue by john-crouch** [wortell/AZSentinel#128]
# Environment

```none
Windows build number: 10.0.19041.572
PowerShell version: 7.0.3
```

# Steps to reproduce

Run any cmdlet included in the module after a valid access token has been acquired and subsequently expired.

# Expected behavior

precheck.ps1 should call Get-AuthToken which should determine that that access token has expired, then acquire a new access token.

# Actual behavior

prescheck.ps1 incorrectly identifies the token as being valid and does not request a new one. This causes the cmdlet to fail:

```
Invoke-WebRequest: C:\GitLocal\AZSentinel\AzSentinel\Private\Get-LogAnalyticWorkspace.ps1:70
Line |
  70 |  … orkspaces = Invoke-webrequest -Uri $uri -Method get -Headers $script: …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | {"error":{"code":"ExpiredAuthenticationToken","message":"The access token expiry UTC time '10/22/2020
     | 5:33:00 PM' is earlier than current UTC time '10/22/2020 6:56:19 PM'."}}
```

# Proposed fix

Changing the logic on line 19 of precheck.ps1 appears to fix the issue
`elseif ($script:accessToken.ExpiresOn.DateTime - [datetime]::UtcNow.AddMinutes(-5) -le 0)`

**Comment by pkhabazi** [comment]
thanks for the great feedback @john-crouch! Will try to test and verify the proposed fix.

**Comment by pkhabazi** [comment]
Tested the proposed solution and works perfect, would you like to create a PR for your proposed fix? thanks in advance for your contributions!
