### ISSUE TITLE
Install-Module AzSentinel Not Working

### ISSUE THREAD

**Issue by kay07949** [wortell/AZSentinel#129]
there is an issue with Install-Module AzSentinel -Scope CurrentUser -Force, It produces the error below:

Install-Package: C:\program files\powershell\7\Modules\PowerShellGet\PSModule.psm1:9709
Line |
9709 |  … talledPackages = PackageManagement\Install-Package @PSBoundParameters
     |                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | No match was found for the specified search criteria and module name 'AzSentinel'. Try
     | Get-PSRepository to see all available registered module repositories.

**Comment by bgelens** [comment]
@kay07949 The PowerShell Gallery is having an outage at the moment. Please try later. Closing this issue as cause is external

**Comment by kay07949** [comment]
thanks !
