### ISSUE TITLE
Bug Report - Alert Rule Creation Failed

### ISSUE THREAD

**Issue by kay07949** [wortell/AZSentinel#145]
I am getting this error when I attempt to update an alert rule:

Alert rule creation failed with message: Unable to initiate class with error: You cannot call a method
on a null-valued expression.

**Comment by pkhabazi** [comment]
Hi @kay07949, can you please share the rule that you are trying to create so that I can test this?

**Comment by acastellano454** [comment]
I am also now getting this same error when pushing rules that used to succeed either via Azure DevOps pipelines or even directly running the New-AzSentinelAlertRule function within a cloud shell:

New-AzSentinelAlertRule -WorkspaceName "LighthouseCustomer2" -DisplayName "test-rule" -Description "test rule" -Severity "High" -Enabled $False -Query "SecurityEvent | where EventID in (567,4657)" -QueryFrequency "PT1H" -QueryPeriod "PT1H" -TriggerOperator "GreaterThan" -TriggerThreshold 0 -SuppressionEnabled $False

**Comment by pkhabazi** [comment]
hi @acastellano454 thanks for the feedback, and example! Just released version 0.6.16 where the issue is fixed. can you please test and verify this?

**Comment by kay07949** [comment]
all good now thank you !
