### ISSUE TITLE
Folder path case insensitivity is not supported in case sensitive file systems. 

### ISSUE THREAD

**Issue by deepanshumarwah** [wortell/AZSentinel#150]
Hi Team ,

I was facing this issue in my windows system using wsl ubuntu 18.04 with powershell 7.1. The Import-AzSentinelAlertRule threw error as it was not able to import the relevant dependent enums and classes because of the case sensitive folder names. I updated the folder names and it started working, so please update these.

https://github.com/wortell/AZSentinel/blob/6f867eba19887b4e5bf6e36031e8fad796937abd/AzSentinel/AzSentinel.psm1#L1

Correct value: $Enums = @( Get-ChildItem -Path $PSScriptRoot\enums\*.ps1 -ErrorAction SilentlyContinue )

https://github.com/wortell/AZSentinel/blob/6f867eba19887b4e5bf6e36031e8fad796937abd/AzSentinel/AzSentinel.psm1#L18

Correct value: '{0}\Classes\{1}.ps1' -f $PSScriptRoot, $class

**Comment by pkhabazi** [comment]
Thanks for the report @deepanshumarwah! Good catch, will fix it in the next release!
