### ISSUE TITLE
Creating Analytic Rules and attaching Playbooks in MSSP tenant fails the first time, then works the second time

### ISSUE THREAD

**Issue by GeorgeAbouSamra** [wortell/AZSentinel#151]
# Environment

Windows build number: Microsoft Windows [Version 10.0.19041.630]
PowerShell version (if applicable): 7.1.0 
Using AzSentinel version: 0.6.16

# Steps to reproduce
Running the following command:

Import-AzSentinelAlertRule -WorkspaceName **WorkspaceName** -SubscriptionId **SubscriptionID** -SettingsFile **"C:\Users\Username\Desktop\TestingAnalyticRules01.json"**

# Expected behavior

The Analytic Rules get created with the Playbooks attached by running the script once.

# Actual behavior
In the JSON file, the playbookName is defined as follows pointing to the MSSP tenant: 

"/subscriptions/**MSSP SubId**/resourceGroups/**MSSP ResourceGroup**/providers/Microsoft.Logic/workflows/**PlaybookName**"

Running Import-AzSentinelAlertRule -WorkspaceName **WorkspaceName** -SubscriptionId **SubscriptionID** -SettingsFile **"C:\Users\<Username>\Desktop\TestingAnalyticRules01.json"** will create the Analytic Rules in Sentinel, however, the Playbooks are not attached to the rules. Even though the rules get created, I am getting the following error and warning:

Error: Unable to create Action for Rule:  with Playbook **PlaybookName** Error: Response status code | does not indicate success: 400 (Bad Request).
WARNING: Unable to find LogicApp **LogicApp Name** under Subscription Id: **SubscriptionId**

It's complaining about Line 2685 |  … ookResult = New-AzSentinelAlertRuleAction @arguments -PlayBookName $( …

![image](https://user-images.githubusercontent.com/36736267/100788338-ef93d300-33e2-11eb-9a54-315fb4e73a4a.png)

Running the same command again attaches the Playbook to the rules successfully.

**Comment by pkhabazi** [comment]
hi @GeorgeAbouSamra thanks for reporting this issue. have you configured at playbook property the resource ID or the name of the playbook? And does it always work the second time or does it happen for each rule the first time?

**Comment by GeorgeAbouSamra** [comment]
Hi @pkhabazi,

I'm using the resource ID of the Playbook that resides in the MSSP tenant. It always attaches the Playbooks the second time I run the script. The first time I run it, I get the errors in the screenshot above. The second time I run the same script, it attaches the Playbook correctly.

With that said, I did some changes last night to Import-AzSentinelAlertRule.ps1 and got it to work, but I'm not sure if those changes would affect something else. Below are the changes I did as a workaround:

**Line 237 in Import-AzSentinelAlertRule.ps1:**
PlaybookResult = New-AzSentinelAlertRuleAction @arguments -PlayBookName **$($body.Properties.playbookName)** -RuleId **$($body.Properties.Name)** -confirm:$false

![image](https://user-images.githubusercontent.com/36736267/101799212-e0dfa700-3ad9-11eb-8f83-c56896d9dbff.png)

**Changed to:**
$PlaybookResult = New-AzSentinelAlertRuleAction @arguments -PlayBookName **$($item.playbookName)** -RuleId **$($body.Name)** -confirm:$false

![image](https://user-images.githubusercontent.com/36736267/101800804-ad058100-3adb-11eb-8a9a-2be58ab96100.png)

Let me know if you need further clarification. Thanks!

**Comment by pkhabazi** [comment]
Thanks for the feedback @GeorgeAbouSamra , Thats really strange because it should be already as you mentioned. In the [Development](https://github.com/wortell/AZSentinel/blob/development/AzSentinel/Public/Import-AzSentinelAlertRule.ps1#L237) branch you can see that's already correct. But somehow it didn't got merged to master branch.. I will include this in the next release.

**Comment by GeorgeAbouSamra** [comment]
Hi @pkhabazi,

Thank you for that. For some reason it's still not working.

If you take a look at line 237, it's correct now.

![image](https://user-images.githubusercontent.com/36736267/102387590-8f825c80-3f9e-11eb-9b9d-db9c4f782495.png)

If you look at line 267, it still points to $($body.Properties.playbookName) instead of $item.playbookName

![image](https://user-images.githubusercontent.com/36736267/102387641-a3c65980-3f9e-11eb-928c-8ad64e893736.png)

Thank you.

**Comment by pkhabazi** [comment]
hi @GeorgeAbouSamra Thank you for the update, Just release version 0.6.20 where all the references should be fixed. please let me know if this fixes your issue. kr, Pouyan

**Comment by GeorgeAbouSamra** [comment]
Hi @pkhabazi,

Thank you! It's working as should now.
