### ISSUE TITLE
Import-AzSentinelHuntingRule error when updating rules

### ISSUE THREAD

**Issue by Jaa9** [wortell/AZSentinel#155]
Running Import-AzSentinelHuntingRule one time works as expected, but successive runs fails with the following error message even if there have been no changes to the hunting rule .json file.

```
Found Differences for hunting rule: HuntingRule01

PropertyName   RefValue                                           DiffValue
------------   --------                                           ---------
Count                                                                     2
IsFixedSize                                                           False
IsReadOnly                                                            False
IsSynchronized                                                        False
Keys                                                          {Value, Name}
SyncRoot                                                      {Value, Name}
Values                  {Persistence,LateralMovement,Exfiltration, tactics}


Import-AzSentinelHuntingRule: /home/vsts/work/_temp/ca80d582-529b-441a-9f07-14b2e4dc0241.ps1:3
Line |
   3 |  Import-AzSentinelHuntingRule -SubscriptionId xxx-xxxx- …
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Exception calling "ShouldProcess" with "1" argument(s):
     | "PowerShell is in NonInteractive mode. Read and Prompt
     | functionality is not available."
```
Command that's been run:
`Import-AzSentinelHuntingRule -SubscriptionId ${{ parameters.SubscriptionId }} -WorkspaceName ${{ parameters.WorkspaceName }} -SettingsFile ${{ parameters.huntingRulesFile }}`

**Comment by pkhabazi** [comment]
hi @Jaa9 thanks for reporting this issue! Are you having this issue also when you use the example Hunting template?

**Comment by pkhabazi** [comment]
hi @Jaa9, this issue is caused because the prompt is asking for confirmation and that's not possible in NonInteractive mode.
you can solve this issue by running the function with the confirm switch set to false:

```PowerShell
Import-AzSentinelHuntingRule -SubscriptionId ${{ parameters.SubscriptionId }} -WorkspaceName ${{ parameters.WorkspaceName }} 
-SettingsFile ${{ parameters.huntingRulesFile }} -Confirm:$false
```

**Comment by pkhabazi** [comment]
hi @Jaa9 I will close the issue because I haven't received any updates. If you are still experiencing  this issue please feel free to reopen. kr, Pouyan
