### ISSUE TITLE
Unable to import YAML files

### ISSUE THREAD

**Issue by nuggetinu** [wortell/AZSentinel#165]
Hi,

I am trying to import the YAML files from the Sentinel Github using the AzSentinelAlertRule command, however this is failing with:

**Import-AzSentinelAlertRule: Cannot validate argument on parameter 'RuleName'**

Using the verbose switch I only get -  'Found compatibel yaml file'

Currently running New-AzSentinelAlertRule.ps1 0.6.18 but also tried with 0.6.8 with same issue. Powershell 7 on Windows 10 v1809.

**Comment by orhanmoye** [comment]
Hi, 

You will need to added your yaml file to the root schema :  https://github.com/wortell/AZSentinel#root-schema

Basically, your yaml file will need to be inside a parent of "Scheduled".  your yaml will need to be an array item within "Scheduled".

Hope that helps.

**Comment by rleal124** [comment]
For Scheduled rule example in below.  More recent version the root schema are changed. 
Scheduled:
- displayName:
 (....)

**Comment by pkhabazi** [comment]
This issue is fixed in the latest version, you can just run the code below without changing the yaml file.

```PowerShell
Import-AzSentinelAlertRule -WorkspaceName "dev" -SettingsFile ./Detections/AuditLogs/UseraddedtoPrivilgedGroups.yaml
```
