### ISSUE TITLE
Feature Request: data connector automation

### ISSUE THREAD

**Issue by MarcOverIP** [wortell/AZSentinel#17]
Although I very much appreciate the creation/deletion of rules in Sentinel, Im also looking for ways to programmatically do the deployment of Sentinel. You have one such function, Set-AzSentinel, which is awesome. But Im missing functions for:

-  enable the data connectors on machines. In the GUI: Home > Azure Sentinel workspaces > Azure Sentinel - Data connectors > $SomeConnectorName > Virtual Machines > $MachineName - click on connect
- configuring and enabling the data connectors. In the GUI: Home > Azure Sentinel workspaces > Azure Sentinel - Data connectors > $SomeConnectorName - click on 'Apply Changes', or in the case of for example the 'Security Events' connector also a configuration check box.

I understand if this is not on the top of you list. These steps in most cases are not done that often. But Im finding myself in a corner case where I need to deploy and completely rebuild entire resource groups for labs, including Sentinel, lots of times :)

**Comment by pkhabazi** [comment]
hi Marc, thanks again for your great feedback. I am glad that you like the work done. 

I cannot follow up with the first point, when I fallow the described path I cannot  continue from "Virtual Machines > $MachineName - click on connect". Can you please add more info to this point

Point 2 is good one, I have already done some testing on this part. Unfortunately there is  to much variation in configuration of each data connector, I need to find a way to dynamically resolve the connector properties. Maybe It's an idea  to start with a set of most used connectors for now, please let me know what you think about it and which are your most used connectors? Maybe we can create a separate PS script to do this for your scenario for the time being?

**Comment by MarcOverIP** [comment]
Hi Pouyan,

Indeed, the option when selected has a different name compared to the 'top bar'. Basically I mean the path of enabling a connector on an (Azure) vm. Let's take the 'Security Events' connector for example. Full click-path is: 
Home > Azure Sentinel workspaces > Azure Sentinel - Data connectors > Security Events > Open connector page > Install agent on Azure Windows Virtual Machine > Download & install agent for Azure Windows Virtual machines > Select the VMS you want > click on connect 

I totally understand to start small with most important data connectors. Imho that would be 'Security Events'. Tbh, other connectors are not really in my interest at this moment. 

Along side that, I would prefer to be able to configure the 'advanced settings' (Home > Azure Sentinel Workspaces > $WorkspaceName > Workspace settings > Advanced Settings) before enabling other data connectors. The reason for this is that it allows me to import Sysmon logs into Sentinel.
But again, I may be in a corner case here.

**Comment by pkhabazi** [comment]
hi Marc,

Thanks for the extra info, that clarifies a lot. So the agent that you want to enable is actually the log analytics workspace agent "MicrosoftMonitoringAgent". You can enable this trough JOSN ARM or PowerShell by running the following:

```PowerShell
$workspaceName = "your workspace name"
$VMresourcegroup = "**"
$VMresourcename = "**"

$workspace = (Get-AzOperationalInsightsWorkspace).Where({$_.Name -eq $workspaceName})

if ($workspace.Name -ne $workspaceName)
{
    Write-Error "Unable to find OMS Workspace $workspaceName. Do you need to run Select-AzureRMSubscription?"
}

$workspaceId = $workspace.CustomerId
$workspaceKey = (Get-AzOperationalInsightsWorkspaceSharedKeys -ResourceGroupName $workspace.ResourceGroupName -Name $workspace.Name).PrimarySharedKey

$vm = Get-AzVM -ResourceGroupName $VMresourcegroup -Name $VMresourcename
$location = $vm.Location

# For Windows VM uncomment the following line
 Set-AzVMExtension -ResourceGroupName $VMresourcegroup -VMName $VMresourcename -Name 'MicrosoftMonitoringAgent' -Publisher 'Microsoft.EnterpriseCloud.Monitoring' -ExtensionType 'MicrosoftMonitoringAgent' -TypeHandlerVersion '1.0' -Location $location -SettingString "{'workspaceId':  '$workspaceId'}" -ProtectedSettingString "{'workspaceKey': '$workspaceKey' }"

# For Linux VM uncomment the following line
# Set-AzVMExtension -ResourceGroupName $VMresourcegroup -VMName $VMresourcename -Name 'OmsAgentForLinux' -Publisher 'Microsoft.EnterpriseCloud.Monitoring' -ExtensionType 'OmsAgentForLinux' -TypeHandlerVersion '1.0' -Location $location -SettingString "{'workspaceId':  '$workspaceId'}" -ProtectedSettingString "{'workspaceKey': '$workspaceKey' }"
```
[source](https://github.com/uglide/azure-content/blob/master/articles/log-analytics/log-analytics-azure-vm-extension.md#enable-the-vm-extension-using-powershell)

Regarding the second point I will keep you posted when we have a working function to enable the solutions.

**Comment by MarcOverIP** [comment]
Thanks, got it to work via templates.

Really looking forward on your solution for the data connectors!
