### ISSUE TITLE
Import-AzSentinelAlertRule fails when passing multiple JSON files

### ISSUE THREAD

**Issue by blanco10kid** [wortell/AZSentinel#177]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](.\CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](##/wiki/FAQs), [closed issues](https://github.com/wortell/AZSentinel/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed), and [open issues](https://github.com/wortell/AZSentinel/issues?q=is%3Aissue+is%3Aopen)).

**How familiar are you with the the source code relevant to this issue?:**

4

**Environment**
> Windows 10
> PowerShell 7.1.3
> AzSentinel 0.6.21

---
**Expected behaviour:**

Import multiple Azure Sentinel Analytic Rules from multiple JSON files saved in a directory

**Actual behaviour:**

I get the following error:

![image](https://user-images.githubusercontent.com/10333513/115435926-fb383880-a1cf-11eb-8022-7b52cfc81b6f.png)

> InvalidOperation: C:\Users\user\Documents\PowerShell\Modules\AzSentinel\0.6.21\AzSentinel.psm1:2698

> Method invocation failed because [System.Management.Automation.PSObject] does not contain a method named 'op_Addition'.

> Import-AzSentinelAlertRule: Cannot validate argument on parameter 'RuleName'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.

Importing these files individually works. I'm running into issues when I try to import multiple JSON files.

**Steps to reproduce:**

1. Place multiple analytic rules (JSON) in a directory
2. Run the following command: 
 `Get-Item .\path\to\directory\*.json | Import-AzSentinelAlertRule -WorkspaceName <workspaceName>`

**Troubleshooting undertaken, and/or other relevant information:**

1. I've tried running the following commands and get the same error:
    `(Get-Item .\*.json).FullName | Import-AzSentinelAlertRule -WorkspaceName <workspaceName>`
    
    `@((Get-Item .\*.json).FullName) | Import-AzSentinelAlertRule -WorkspaceName <workspaceName>`
    
    `$tmp = @((Get-Item .\*.json).FullName);  foreach ($i in $tmp) {Import-AzSentinelAlertRule -WorkspaceName <workspaceName> -SettingsFile $i`

**Comment by pemontto** [comment]
Can you post samples of your JSON files to reproduce the issue?

**Comment by blanco10kid** [comment]
@pemontto Here's a sample JSON file. The syntax is exactly the same in all the other JSON files.

```json
{
	"Scheduled": {
		"displayName": "AnalyticRuleTest", 
		"description": "Sample JSON file for the following Github issue: https://github.com/wortell/AZSentinel/issues/177", 
		"severity": "Medium", 
		"enabled": true, 
		"query": "SecurityAlert\r\n| where ProviderName == \"MDATP\"\r\n| take 100", 
		"queryFrequency": "PT30M", 
		"queryPeriod": "PT30M", 
		"triggerOperator": "GreaterThan", 
		"triggerThreshold": 0, 
		"suppressionDuration": "PT5H", 
		"suppressionEnabled": false, 
		"tactics": [
			"CredentialAccess", 
			"Discovery", 
			"Collection", 
			"InitialAccess"
		], 
		"aggregationKind": "SingleAlert", 
		"createIncident": true, 
		"groupConfiguration": {
			"enabled": false, 
			"reopenClosedIncident": false, 
			"lookbackDuration": "PT1H", 
			"entitiesMatchingMethod": "All", 
			"groupByEntities": [
				"Host", 
				"IP"
			]
		}
	}
}

```

**Comment by pemontto** [comment]
@blanco10kid each of the [root level rule types](https://github.com/wortell/AZSentinel#root-schema) should be an array `[]` not an object `{}`. This should work for you:

```json
{
    "Scheduled": [
        {
            "displayName": "AnalyticRuleTest",
            "description": "Sample JSON file for the following Github issue: https://github.com/wortell/AZSentinel/issues/177",
            "severity": "Medium",
            "enabled": true,
            "query": "SecurityAlert\r\n| where ProviderName == \"MDATP\"\r\n| take 100",
            "queryFrequency": "PT30M",
            "queryPeriod": "PT30M",
            "triggerOperator": "GreaterThan",
            "triggerThreshold": 0,
            "suppressionDuration": "PT5H",
            "suppressionEnabled": false,
            "tactics": [
                "CredentialAccess",
                "Discovery",
                "Collection",
                "InitialAccess"
            ],
            "aggregationKind": "SingleAlert",
            "createIncident": true,
            "groupConfiguration": {
                "enabled": false,
                "reopenClosedIncident": false,
                "lookbackDuration": "PT1H",
                "entitiesMatchingMethod": "All",
                "groupByEntities": [
                    "Host",
                    "IP"
                ]
            }
        }
    ]
}
```

Import using `Import-AzSentinelAlertRule -SettingsFile ./your_json_file.json`

**Comment by pkhabazi** [comment]
@blanco10kid can you please verify if the above proposed solution works for you?

**Comment by blanco10kid** [comment]
> @blanco10kid can you please verify if the above proposed solution works for you?

Can confirm that the solution above worked. Thanks team!
