### ISSUE TITLE
Import-AzSentinelAlertRule Informational Severity - user error?

### ISSUE THREAD

**Issue by nm67326y9** [wortell/AZSentinel#20]
Very impressed so far and having great success with Import-AzSentinelAlertRule (JSON) except for

"severity": "Informational"

which imports without error but has a "High" severity on the portal that needs a manual change.

**Comment by pkhabazi** [comment]
thanks for your feedback, I have been testing this issue and its related to how enum's get converted to JSON in the webrequest process. Will be solved in the next pr

**Comment by nm67326y9** [comment]
Tested PR 'smallchanges' and version 0.6.1 fixes this issue. Many thanks Pouyan.

**Comment by pkhabazi** [comment]
Thanks for testing @nm67326y9 , AzSentinel module version 0.6.1 is now available in the PowerShell Gallery: https://www.powershellgallery.com/packages/AzSentinel/0.6.1
