### ISSUE TITLE
The example in Get-AzSentinelAlertRule.md doesn't work

### ISSUE THREAD

**Issue by garybushey** [wortell/AZSentinel#26]
The example to show all the rules:
Get-AzSentinelAlertRule -WorkspaceName "" -RuleName "","" 

Throws an error stating there needs to be a value for WorkspaceName.  Even with filling in the WorkspaceName, an error is thrown stating that RuleName cannot be null, empty, or has an element of the argument collection that is null

**Comment by pkhabazi** [comment]
hi @garybushey , thanks for your feedback. Rulename parameter is not required, but if you define it then the value cannot be null or empty.

Try running the following to get a list of all the rules:

```PowerShell
Get-AzSentinelAlertRule -WorkspaceName "Your workspace name"
```

**Comment by pkhabazi** [comment]
no response from user, closing issue.
