### ISSUE TITLE
Feature Request: add force flag when importing / changing a rule

### ISSUE THREAD

**Issue by sbroosnokia** [wortell/AZSentinel#34]
Hi, it would be convenient to have a -Force update flag in case a rule setting was changed. Current behavior asks for confirmation to the end user. However this limits the automation of using this module in CI pipelines.

Same comment for the other type of settings (e.g. hunting queries), a Force flag would be useful

**Comment by pkhabazi** [comment]
hi @sbroosnokia thanks for your feedback, this is actually already implemented in all the functions, you can use "-Confirm:$false" switch to skip the confirm question. please let me know if this is not working for you.

**Comment by sbroosnokia** [comment]
Ah thanks! I misinterpreted this flag. I thought it always forced confirmation, even if nothing was changed. Issue can be closed
