### ISSUE TITLE
Is there a way to increase returned results past 200 entries?

### ISSUE THREAD

**Issue by jeffhoyo** [wortell/AZSentinel#35]
It appears when running Get-AzSentinelIncident, it only returns the last 200 results, whether they are open or closed. We were not able to find a limit in the AzSentinel.psm1 code for the function.

It would be nice to increase or set a time frame in the script an increase results past 200 returned cases.

**Comment by pkhabazi** [comment]
hi @jeffhoyo thanks for your reply, I will add a switch -all that you can use to pull all the incidents, I am also working to add some additional filter options like, only opened incident, closed, time range etc. in the feature  release. please let me know if you have some filter ideas.
