### ISSUE TITLE
Time Format conflict

### ISSUE THREAD

**Issue by lunchbox-rcl** [wortell/AZSentinel#38]
# Environment
```
$PSVersionTable
Name                           Value
----                           -----
PSVersion                      7.0.0-rc.2
PSEdition                      Core
GitCommitId                    7.0.0-rc.2
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

Get-Module AzSentinel

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     0.6.1                 AzSentinel                          {Get-AzSentinelAlertRule, Get-AzSentinelHuntingRule, Get-AzSentinelIncident, Import-AzSentinelAlertRule…}
```

# Steps to reproduce

1. Get a singular analytic rule and store it as a PSCustomObject (Ex: `$rule = Get-AzSentinelAlertRule -RuleName $ruleName`)
2. Run `New-AzSentinelAlertRule -Severity $rule.severity -Query $rule.query -QueryFrequency $rule.queryFrequency -QueryPeriod $rule.queryPeriod -TriggerOperator $rule.triggerOperator -TriggerThreshold $rule.triggerThreshold -SuppressionDuration $rule.suppressionDuration -SuppressionEnabled $rule.suppressionEnabled -DisplayName "Chris2" -Enabled $rule.enabled -Description "just copying stuff" -Tactics $rule.tactics`

# Expected behavior

Expect to have a similar rule created in Sentinel

# Actual behavior

New-AzSentinelAlertRule: Unable to invoke webrequest with error message: The string 'PTPT5M' is not a valid TimeSpan value. ISO 8601 format is expected. Path 'Properties.QueryFrequency'

**Comment by pkhabazi** [comment]
hi @lunchbox-rcl thanks for your feedback, this is a known bug and is already solved in the version available in development branch. The issue is that in the past I added "PT" static in de class definition, and if you do a Get and New you get double PTPT. please let me know if you are able to test the version in development branch.

**Comment by lunchbox-rcl** [comment]
@pkhabazi - Awesome.  Thanks.  I can't test on this machine.  I'll try to get it on another box.
