### ISSUE TITLE
Feature Request: address a workspace to Set-AzSentinel from pipeline

### ISSUE THREAD

**Issue by MauRiEEZZZ** [wortell/AZSentinel#4]
# Summary of the new feature/enhancement

It would be nice if the object(s) that returned from 
New-AzOperationalInsightsWorkspace (speaking of long functionnames ;-) )
or 
Get-AzOperationalInsightsWorkspace
could be used to provision Sentinel on it using Set-AzSentinel.
# Proposed technical implementation details (optional)

**Comment by pkhabazi** [comment]
we have "Get-LogAnalyticWorkspace" as a private function, This function is used to test if the workspace exists and returns some base uri elements on script scope
