### ISSUE TITLE
SubscriptionId parameter not taken into account correctly in New-AzSentinelAlertRuleAction

### ISSUE THREAD

**Issue by sbroosnokia** [wortell/AZSentinel#42]
Hi, Thanks for implementing this functionality.
I notice one issue though: when I specify -SubscriptionId, it does not seem to be taken into account correctly. The AlertRuleAction fails, but points to a different subscriptionId then specified with -SubscriptionId.

Unable to find LogicApp <redacted-out> under Subscription Id: <redacted-out>
This failure is not pointing to the Subscription Id I specified with -SubscriptionId

**Comment by pkhabazi** [comment]
hi @sbroosnokia thanks for your feedback. So the logic app and Azure Sentinel are not in the same subscription in your test, is that correct?

**Comment by sbroosnokia** [comment]
They are in the same subscription, but in a different resourcegroup

**Comment by pkhabazi** [comment]
Can you send me the command and also the verbose output? And does the function work if you don't specify a subscriptionID or use the JSON layout?

**Comment by sbroosnokia** [comment]
It also doesn't work when omitting the subscriptionId. I did not try the JSON layout. Logs have been redacted and shared over mail

**Comment by pkhabazi** [comment]
Thanks for the great feedback. Founded the problem and created a pr for the solution.. will merged in coming days and release a new version

**Comment by sbroosnokia** [comment]
Hi, Thanks for the swift reply. That pull request seems to fix it. I could use the module to attach a playbook to my rule.
