### ISSUE TITLE
Logic apps configured using the playbookName parameter not getting triggered

### ISSUE THREAD

**Issue by sbroosnokia** [wortell/AZSentinel#47]
Hi,
This behavior is hard to describe but it seems that logic apps that get configured via powershell do not get triggered correctly.

- If I configure a logic app via Gui, everything is fine and it will get triggered by alerts
- If I configure it using the playbookName paramter, it appears in Gui to be set correct (it is selected in the automation tab). But the playbook does not get triggered on alert. This behavior is reproducible when setting the logic app on a new alert, and while setting by updating an existing alert.

It is not sure to me if this is a consequence of configuring a playbook over API (and if the problem is at Microsoft side) or if this is an issue of the PS module

**Comment by pkhabazi** [comment]
hi @sbroosnokia thanks for the feedback. sorry for the delay I have been very bussie the last couple of days. I have found the problem in the AzSentinel module, will try to fix it in coming days. 
**problem description:** to be able to call the logicApp you need to provide a sas key, when building up the uri I have made a mistake in getting the sas key.
