### ISSUE TITLE
 Cannot validate argument on parameter "Property"

### ISSUE THREAD

**Issue by SamantJaitli** [wortell/AZSentinel#48]
Trying to run a script> 
Get-AzSentinelHuntingRule -SubscriptionId $Subscription -WorkspaceName $Workspace 

But getting the error everytime : Unable to get hunting rules with error code: Cannot validate argument on parameter "Property". The argument is null or empty.

If WorkspaceName is the only required parameter why is it showing this error?

**Comment by pkhabazi** [comment]
hi @SamantJaitli thanks for your feedback. this is indeed a bug and I have created a pr which will solve this issue.
