### ISSUE TITLE
Get Sentinel Incidents

### ISSUE THREAD

**Issue by garfield-p** [wortell/AZSentinel#54]
# Expected behavior

To get a list with all open incidents.

To get all Incidnets from Sentinel

# Actual behavior

ConvertFrom-Json: C:\Users\A002633\Documents\PowerShell\Modules\AzSentinel\0.6.2\AzSentinel.psm1:810
Line |
 810 |                  ($incident.Content | ConvertFrom-Json).value | ForEac …
     |                                       ~~~~~~~~~~~~~~~~
     | Cannot bind argument to parameter 'InputObject' because it is null.

**Comment by pkhabazi** [comment]
thanks for your feedback, this bug is already covered in issue #48.
I am currently working to release a new version where this bug is solved.
