### ISSUE TITLE
Import YAML Files

### ISSUE THREAD

**Issue by kay07949** [wortell/AZSentinel#58]
Hi, 

i tried to import the YAML files from the Sentinel Github using the Import-AzSentinel command, however this failed without any error messages. 

https://github.com/Azure/Azure-Sentinel/tree/master/Detections - ideally i wanted to deploy quiet a few of these alert rules via YML files.

**Comment by pkhabazi** [comment]
@kay07949 thanks for the feedback, can you share your error message with us?

**Comment by pemontto** [comment]
@kay07949 try running with the -Verbose flag to see why it's failing. E.g.

```powershell
Import-AzSentinelAlertRule -Verbose -SettingsFile Detections/AWSCloudTrail/AWS_ChangeToVPC.yaml
```

**Comment by pkhabazi** [comment]
It is time related and is fixed with your proposed pr, great work @pemontto 
```PowerShell
The string 'PT1D' is not a valid TimeSpan value. ISO 8601 format is expected. Path 'Properties.QueryFrequency'
```
