### ISSUE TITLE
Enable Alert Rules from Templates 

### ISSUE THREAD

**Issue by kay07949** [wortell/AZSentinel#64]
I think a useful feature would be a command let to enable the a rule templates, this feature would be useful if someone is required to enable it across multiple sentinel workspaces

**Comment by pkhabazi** [comment]
hi @kay07949, have you tried using the enabled property in the JSON format, or do you prefer a separate enable/disable-AzSentinelAlertrule command?
```JSON
{
  "analytics": [
    {
      "displayName": "string",
      "description": "string",
      "severity": "High",
      **"enabled": true,**
      "query": "SecurityEvent | where EventID == \"4688\" | where CommandLine contains \"-noni -ep bypass $\"",
      "queryFrequency": "5H",
      "queryPeriod": "5H",
      "triggerOperator": "GreaterThan",
      "triggerThreshold": 5,
      "suppressionDuration": "6H",
      "suppressionEnabled": false,
      "tactics": [
        "Persistence",
        "LateralMovement",
        "Collection"
      ],
      "playbookName": "string"
    }
  ]
}
```

**Comment by kay07949** [comment]
I will give that a try thanks, so I populate the display name with the rule template name in json and enable ?

I think it will be ideal to have a command in powershell to enable the rule templates without json files, that way we can have a text file with all the alert rules we want to enable in our devops pipeline and enable disable to all the environments.

**Comment by kay07949** [comment]
i've tried using the json file below and it didnt work:

`{
  "analytics": [ 
{
        "displayName": "Brute force attack against Azure Portal",
        "description": "Test",
        "enabled": true
]
}
`
