### ISSUE TITLE
AzSentinel commandlets should support PowerShell minimum version 5.0 

### ISSUE THREAD

**Issue by cp-sc-source** [wortell/AZSentinel#67]
# Summary of the new feature/enhancement

# Proposed technical implementation details (optional)

**Comment by cp-sc-source** [comment]
AzSentinel commandlets should support PowerShell minimum version 5.0

**Comment by pkhabazi** [comment]
hi @cp-sc-source thanks for your feedback. Is there a specific scenario where you don't have access to PowerShell 6.2 or higher? very curious about your scenario.

**Comment by cp-sc-source** [comment]
Hi @pkhabazi - Powershell 5.x is still good and not old enough to drop its backward compatibility with  AzSentinel command lets.  Most customers dont want to upgrade not should we be asking them. Hope to see commandlets supporting minimum ps 5x version.

**Comment by cp-sc-source** [comment]
@pkhabazi - Are you planning to extend this module to support powershell verion 5.x ?

**Comment by pkhabazi** [comment]
@cp-sc-source sorry for the late response, I have being testing and trying to make AzSentinel available on Windows PowerShell. you can follow the work [here](https://github.com/wortell/AZSentinel/tree/feature/WindowsPowerShell).
Unfortunately there are a couple of problems that aren't easy to solve at the moment. mostly related on how I use and convert the data. So, for now I have decided not to spend more time on trying to make AzSentinel available for Windows PowerShell. I really advice you to switch to a newer versions or start using [Cloud Shell](https://docs.microsoft.com/en-us/azure/cloud-shell/overview).

kr,
Pouyan
