### ISSUE TITLE
Bug Report - Get-AzSentinelHuntingRule

### ISSUE THREAD

**Issue by cybermiu2** [wortell/AZSentinel#75]
# Environment

Powershell 7.0, Az 3.8.0, Yaml 0.4.2

# Steps to reproduce

 Get-AzSentinelHuntingRule -WorkspaceName \<workspace name\>

# Expected behavior

Based on the material, the expected behavior is to return the hunting rules configured

# Actual behavior

It is returning me the list of queries under query explorer

**Comment by pkhabazi** [comment]
hi @cybermiu2 thanks for your feedback! you can use the filter option to only get the hunting rules configured

```PowerShell
Get-AzSentinelHuntingRule -WorkspaceName ""-Filter 'Hunting Queries'
```
