### ISSUE TITLE
Guidance - Next Release and imported rules

### ISSUE THREAD

**Issue by fbinotto** [wortell/AZSentinel#79]
First of all, thanks so much for this module as it is extremely useful.

Any idea when the new release is coming out?

Also, when I use the Import-AzSentinelAlertRule to import one of the Template rules, the templates are not flagged as IN USE as they would if you created a new rule based on the template directly from the Azure portal.

![image](https://user-images.githubusercontent.com/17077662/84964715-2be2b800-b150-11ea-8ab8-b8a8bf497e26.png)

Thanks
Felipe

**Comment by pkhabazi** [comment]
hi @fbinotto thanks for your feedback. Is the print screen from the "Relevant analytic templates" in the DataConnecter settings?
From what I can see this windows is updated and doesn't contain the "in use" flag anymore.

For now I will close this issue, please feel free to open the issue if it's still applicable.

kr,
Pouyan
