### ISSUE TITLE
Unable to use Disable-AzSentinelAlertRule or Enable-AzSentinelAlertRule

### ISSUE THREAD

**Issue by pemontto** [wortell/AZSentinel#84]
# Environment

```powershell
> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.0.3
PSEdition                      Core
GitCommitId                    7.0.3
OS                             Darwin 18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

# Steps to reproduce

Attempt to disable a scheduled rule that is currently enabled.

```powershell
Disable-AzSentinelAlertRule -Verbose -Debug -SubscriptionId XXX -WorkspaceName XXX -RuleName "(Preview) TI map Email entity to OfficeActivity"
```

# Expected behavior

The rule gets disabled.

# Actual behavior

The command produces errors when, I'm guessing, it tries to build the Scheduled Alert rule object:

```powershell
<snip>
InvalidOperation: /x/powershell/Modules/AzSentinel/0.6.5/AzSentinel.psm1:644
Line |
 644 |                  $bodyAlertProp = [AlertProp]::new(
     |                                   ~~~~~~~~~~~
     | Unable to find type [AlertProp].

MethodException: /x/powershell/Modules/AzSentinel/0.6.5/AzSentinel.psm1:648
Line |
 648 |                  $body = [AlertRule]::new(
     |                  ~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot find an overload for "new" and the argument count: "2".
<snip>
Disable-AzSentinelAlertRule: Response status code does not indicate success: 400 (Bad Request).
```

**Comment by pemontto** [comment]
Hoping this was a simple one, but changing `AlertProp` to `ScheduledAlertProp` didn't fix it. The `$rule` object properties are seemingly treated as a single argument to the constructor rather than the individual key/values.

[AzSentinel/Public/Disable-AzSentinelAlertRule.ps1:63-65](https://github.com/wortell/AZSentinel/blob/52500c7921be40c3fe99bffede64e19da6bc0c8d/AzSentinel/Public/Disable-AzSentinelAlertRule.ps1#L63-65)
```powershell
$bodyAlertProp = [AlertProp]::new(
    ($rule | Select-Object * -ExcludeProperty lastModifiedUtc, etag, id)
)
```

**Comment by rleal124** [comment]
I am cross the same situation. I am sure works before last commit.  
Do have some workaround?

**Comment by pemontto** [comment]
I haven't been able to get this working either. Currently on 0.6.10

```powershell
Get-Command -Module AzSentinel Disable-AzSentinelAlertRule

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Function        Disable-AzSentinelAlertRule                        0.6.10     AzSentinel
```

```powershell
Get-Command -Module AzSentinel Enable-AzSentinelAlertRule

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Function        Enable-AzSentinelAlertRule                         0.6.10     AzSentinel
```

```powershell
Disable-AzSentinelAlertRule -WorkspaceName $Workspace -RuleName $RuleName -Verbose -Debug
<SNIP>
InvalidOperation: /Users/test/.local/share/powershell/Modules/AzSentinel/0.6.10/AzSentinel.psm1:3376
Line |
3376 |                  $bodyAlertProp = [AlertProp]::new(
     |                                   ~~~~~~~~~~~
     | Unable to find type [AlertProp].

MethodException: /Users/test/.local/share/powershell/Modules/AzSentinel/0.6.10/AzSentinel.psm1:3380
Line |
3380 |                  $body = [AlertRule]::new(
     |                  ~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot find an overload for "new" and the argument count: "2".
```

**Comment by rleal124** [comment]
@pemontto I know works before, because I running a script last week and works well. Yesterday i starting have the issues with disable the AlertRule

**Comment by pemontto** [comment]
For now you can have a look at your previous versions and rollback to a version that works

```powershell
Get-Module -ListAvailable AzSentinel
```

Rollback
```powershell
Import-Module AzSentinel -RequiredVersion "0.6.8" -Force
```

**Comment by rleal124** [comment]
I am try using the 0.6.10, 0.6.8 and 0.6.5 and I still have same error.  

Disable-AzSentinelAlertRule -SubscriptionId $SubscriptionId -WorkspaceName $WorkspaceName -RuleName $RuleName

InvalidOperation: C:\Users\user\Documents\PowerShell\Modules\AzSentinel\0.6.5\AzSentinel.psm1:644
Line |
 644 |                  $bodyAlertProp = [AlertProp]::new(
     |                                   ~~~~~~~~~~~
     | Unable to find type [AlertProp].

MethodException: C:\Users\user\Documents\PowerShell\Modules\AzSentinel\0.6.5\AzSentinel.psm1:648
Line |
 648 |                  $body = [AlertRule]::new(

Disable-AzSentinelAlertRule: Response status code does not indicate success: 400 (Bad Request).
     |                  ~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot find an overload for "new" and the argument count: "2".

**Comment by pkhabazi** [comment]
@rleal124 thanks for the feedback, I see what's broken. Already fixed the issue for disable and enable function. Will merge this.

**Comment by rleal124** [comment]
@pkhabazi Thanks for your feedback.

**Comment by pkhabazi** [comment]
@pemontto and @rleal124 please update to version 0.6.11, problem should be fixed in this version

**Comment by rleal124** [comment]
@pkhabazi Thanks, I tested now and works well. Many thanks for your support.
