### ISSUE TITLE
Not able to import rules

### ISSUE THREAD

**Issue by akapv** [wortell/AZSentinel#85]
Hello Folks!
Any ideas about what´s causing this?

PS C:\Windows\System32> Set-AzSentinel -WorkspaceName "WorkpaceBlah"
Azure Sentinel is already enabled on WorkpaceBlah and status is: OK

PS C:\Windows\System32> Import-AzSentinelAlertRule -WorkspaceName "WorkpaceBlah" -SettingsFile C:\temp\sentinel_attack_rules.json
Import-AzSentinelAlertRule: Unable to connect to APi to get Analytic rules with message: Cannot validate argument on parameter 'RuleName'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.

**Comment by pkhabazi** [comment]
hi @akapv thanks for creating an issue. This issue is often related to a wrong template layout. [here ](https://github.com/wortell/AZSentinel/blob/master/examples/AlertRules.json)you can find an example file 

please let me know if this solves your issue.

**Comment by Castaldio86** [comment]
@akapv I had the same issue when I didn't export with ... | ConvertTo-Json | Out-File ...
