### ISSUE TITLE
Update-AzSentinelIncident deletes various incident properties

### ISSUE THREAD

**Issue by jholtmann** [wortell/AZSentinel#89]
# Environment

```none
Windows build number: 10.0.19041.450
PowerShell version (if applicable): 7.0.3

Any other software? No
```

# Steps to reproduce

Run `Update-AzSentinelIncident` to update an existing incident

# Expected behavior

Ticket with matching incident number has properties provided to cmdlet updated. Properties not provided are not altered.

# Actual behavior

Available cmdlet properties work correctly, but the following incident properties are irreversibly deleted:
- TotalComments
- Metrics
- RelatedAlertIds
- RelatedAlertProductNames
- Description
- FirstAlertTimeGenerated
- LastAlertTimeGenerated
- Owner.Name
- Owner.Email
- Owner.ObjectId

**Comment by jholtmann** [comment]
Ran into this issue when testing the cmdlet on some test incidents. I was lucky that I did not need these incidents, as lots of data was lost after the update. This is a fairly easy fix, since all the missing parameters are retrieved by `Get-AzSentinelIncident` and can be passed to the API PUT.

If this functionality is not intentional, please let me know and I can submit a pull request with a fix. If it is intentional, I recommend adding notes to the documentation so people do not accidentally wipe out incident data using this command.

**Comment by pkhabazi** [comment]
hi @jholtmann thanks for your great feedback! I have tested the described issue and the properties mentioned are getting deleted indeed. Please feel free to create a PR if you already have a working fix!
