### ISSUE TITLE
Get and remove Hunting Rules broken

### ISSUE THREAD

**Issue by darvid** [wortell/AZSentinel#93]
# Environment

```none
Windows build number: Version 10.0.19042.487
PowerShell version (if applicable): 5.1.19041.1
AzSentinel version: 0.6.5 (latest)
```

# Steps to reproduce

Call `Get-AzSentinelHuntingRule` or `Remove-AzSentinelHuntingRule`  with `-RuleName` set to the display name of an existing hunting rule.

# Expected behavior

Get should return filtered hunting rules, and remove should remove the filtered hunting rules.

# Actual behavior

After debugging the underlying API requests, it seems like Azure is returning a different response than AzSentinel is expecting. It looks like the API version hardcoded in AzSentinel has no effect, and Azure is returning the newer/latest response structure regardless (assuming the hunting rules functions worked in the past). 

Specifically, I think AzSentinel should be using the `DisplayName` property in the response rather than `name` for hunting rules. `name` contains a guid now, while `DisplayName` is the actual name that should be filtered on.

**Comment by pkhabazi** [comment]
hi @darvid thanks for your great detailed feedback! I have added the -Filter option that you can use to only get "Custom Queries" for example. Also fixed the response from the API and updated the remove function. proposed fixes will be released in next version! Please let me now if you are still missing feature. Kr Pouyan
