### ISSUE TITLE
Alert rule creation failed with message: Unable to initiate class with error: Cannot find an overload

### ISSUE THREAD

**Issue by sunilkhuttan** [wortell/AZSentinel#97]
# Environment

I am using Azure DevOps to deploy Azure components (https://techcommunity.microsoft.com/t5/azure-sentinel/deploying-and-managing-azure-sentinel-as-code/ba-p/1131928)

Any other software?
```

# Steps to reproduce

Run the pipeline to deploy analytics rules
Method invoke
New-AzSentinelAlertRule -WorkspaceName $Workspace -DisplayName $rule.displayName -Description $rule.description -Severity $rule.severity -Enabled $rule.enabled -Query $rule.query -QueryFrequency $rule.queryFrequency -QueryPeriod $rule.queryPeriod -TriggerOperator $rule.triggerOperator -TriggerThreshold $rule.triggerThreshold -SuppressionDuration $rule.suppressionDuration -SuppressionEnabled $rule.suppressionEnabled -Tactics $rule.tactics -PlayBookName $rule.playbookName

# Expected behavior

The rules in the analytics json file should be deployed to sentinel

# Actual behavior

I am getting the following error 
Alert rule creation failed with message: Unable to initiate class with error: Cannot find an overload for "new" and the argument count: "4".

Could you please advise if there is a solution ?
I have attached an image of New-AzSentinelAlertRule.ps1 codes where i think it fail
<img width="559" alt="Sentinel-analytics issue" src="https://user-images.githubusercontent.com/12437274/93846852-9cb5e500-fce8-11ea-83fa-60b84ffc7d65.PNG">

**Comment by pkhabazi** [comment]
@sunilkhuttan thanks for reporting this, this is often related to the fact that the JOSN template doesn't contain all the properties. can you share your template for further support. can you also share which version of AzSentinel you are using currently?

**Comment by sunilkhuttan** [comment]
@pkhabazi thanks for replying. I am using AzSentinel version 0.6.6. The script was working fine till yesterday (around 20 hours ago), there was no issue . I am invoking the method as follow
New-AzSentinelAlertRule -WorkspaceName $Workspace -DisplayName $rule.displayName -Description $rule.description -Severity $rule.severity -Enabled $rule.enabled -Query $rule.query -QueryFrequency $rule.queryFrequency -QueryPeriod $rule.queryPeriod -TriggerOperator $rule.triggerOperator -TriggerThreshold $rule.triggerThreshold -SuppressionDuration $rule.suppressionDuration -SuppressionEnabled $rule.suppressionEnabled -Tactics $rule.tactics -PlayBookName $rule.playbookName

**Comment by sunilkhuttan** [comment]
This is the json I am passing
{
      "severity": "High",
      "query": "let detectionTime = 1d;\nlet joinLookback = 14d;\nAuditLogs\n| where TimeGenerated > ago(detectionTime)\n| where LoggedByService =~ \"Core Directory\"\n| where Category =~ \"ApplicationManagement\"\n| where OperationName =~ \"Consent to application\"\n| where TargetResources has \"mailboxsettings\"\n| extend AppDisplayName = TargetResources.[0].displayName\n| extend AppClientId = tolower(TargetResources.[0].id)\n| where AppClientId !in ((externaldata(knownAppClientId:string, knownAppDisplayName:string)[@\"https://raw.githubusercontent.com/Azure/Azure-Sentinel/master/Sample%20Data/Feeds/Microsoft.OAuth.KnownApplications.csv\"] with (format=\"csv\")))\n| extend ConsentFull = TargetResources[0].modifiedProperties[4].newValue\n| parse ConsentFull with * \"ConsentType: \" GrantConsentType \", Scope: \" GrantScope1 \"]\" *\n| where ConsentFull contains \"contacts.read\" and ConsentFull contains \"user.read\" and ConsentFull contains \"mail.read\" and ConsentFull contains \"notes.read.all\" and ConsentFull contains \"mailboxsettings.readwrite\" and ConsentFull contains \"Files.ReadWrite.All\"\n| where GrantConsentType != \"AllPrincipals\" // NOTE: we are ignoring if OAuth application was granted to all users via an admin - but admin due diligence should be audited occasionally\n| extend GrantIpAddress = iff(isnotempty(InitiatedBy.user.ipAddress), InitiatedBy.user.ipAddress, InitiatedBy.app.ipAddress)\n| extend GrantInitiatedBy = iff(isnotempty(InitiatedBy.user.userPrincipalName),InitiatedBy.user.userPrincipalName, InitiatedBy.app.displayName)\n| extend GrantUserAgent = iff(AdditionalDetails[0].key =~ \"User-Agent\", AdditionalDetails[0].value, \"\")\n| project TimeGenerated, GrantConsentType, GrantScope1, GrantInitiatedBy, AppDisplayName, GrantIpAddress, GrantUserAgent, AppClientId, OperationName, ConsentFull, CorrelationId\n| join kind = leftouter (AuditLogs\n| where TimeGenerated > ago(joinLookback)\n| where LoggedByService =~ \"Core Directory\"\n| where Category =~ \"ApplicationManagement\"\n| where OperationName =~ \"Add service principal\"\n| extend AppClientId = tolower(TargetResources[0].id)\n| extend AppReplyURLs = iff(TargetResources[0].modifiedProperties[1].newValue has \"AddressType\", TargetResources[0].modifiedProperties[1].newValue, \"\")\n| distinct AppClientId, tostring(AppReplyURLs)\n)\non AppClientId\n| join kind = innerunique (AuditLogs\n| where TimeGenerated > ago(joinLookback)\n| where LoggedByService =~ \"Core Directory\"\n| where Category =~ \"ApplicationManagement\"\n| where OperationName =~ \"Add OAuth2PermissionGrant\" or OperationName =~ \"Add delegated permission grant\"\n| extend GrantAuthentication = tostring(TargetResources[0].displayName)\n| extend GrantOperation = OperationName\n| project GrantAuthentication, GrantOperation, CorrelationId\n) on CorrelationId\n| project TimeGenerated, GrantConsentType, GrantScope1, GrantInitiatedBy, AppDisplayName, AppReplyURLs, GrantIpAddress, GrantUserAgent, AppClientId, GrantAuthentication, OperationName, GrantOperation, CorrelationId, ConsentFull",
      "queryFrequency": "P1D",
      "queryPeriod": "P14D",
      "triggerOperator": "GreaterThan",
      "triggerThreshold": 0,
      "suppressionDuration": "PT1H",
      "suppressionEnabled": false,
      "incidentConfiguration": {
        "createIncident": false,
        "groupingConfiguration": "@{enabled=True; reopenClosedIncident=False; lookbackDuration=PT5H; entitiesMatchingMethod=All; groupByEntities=Account Ip Host Url}"
      },
      "eventGroupingSettings": {
        "aggregationKind": "SingleAlert"
      },
      "displayName": "Suspicious application consent similar to O365 Attack Toolkit",
      "enabled": true,
      "description": "This will alert when a user consents to provide a previously-unknown Azure application with the same OAuth permissions used by the MDSec O365 Attack Toolkit (https://github.com/mdsecactivebreach/o365-attack-toolkit).\nThe default permissions/scope for the MDSec O365 Attack toolkit are contacts.read, user.read, mail.read, notes.read.all, mailboxsettings.readwrite, and files.readwrite.all.\nConsent to applications with these permissions should be rare, especially as the knownApplications list is expanded, especially as the knownApplications list is expanded. Public contributions to expand this filter are welcome!\nFor further information on AuditLogs please see https://docs.microsoft.com/azure/active-directory/reports-monitoring/reference-audit-activities.",
      "tactics": [
        "CredentialAccess",
        "DefenseEvasion"
      ],
      "playbookName": "",
      "kind": "Scheduled"
    }

**Comment by pkhabazi** [comment]
Thanks for the input, I released yesterday version 0.6.6. There is probably a change breaking the deployment. I will test this later today.
fastest solution for you at the moment would be following:
open "Scripts/CreateAnalyticsRulesAPI.ps1" and replace line 12 'Install-Module AzSentinel -Scope CurrentUser -Force' with below example
```PowerShell
Install-Module AzSentinel -RequiredVersion 0.6.5 -Scope CurrentUser -Force
```

**Comment by sunilkhuttan** [comment]
Great, thanks @pkhabazi

**Comment by pkhabazi** [comment]
@sunilkhuttan can you also try using the Import-AzSentinelAlertRule function instead of New-AzSentinelAlertRule

```PowerShell
Import-AzSentinelAlertRule -WorkspaceName -SettingsFile template.json
```

see [doc](https://github.com/wortell/AZSentinel/blob/master/docs/Import-AzSentinelAlertRule.md)

here you can find an example template file:
https://github.com/wortell/AZSentinel/blob/master/examples/AlertRules.json

**Comment by kay07949** [comment]
I am getting the same error my files i am deploying via devops was working fine untill recently

**Comment by pkhabazi** [comment]
hi @sunilkhuttan , just release version 0.6.7 where the bug should be solved. thanks for your feedback! kr Pouyan
