### ISSUE TITLE
KQL querry is causing an error in analytics-rules.jason Bug Report

### ISSUE THREAD

**Issue by alphaomega0** [wortell/AZSentinel#98]
![image](https://user-images.githubusercontent.com/17535650/93918030-c3205400-fcd9-11ea-92f9-a1478814654e.png)
![image](https://user-images.githubusercontent.com/17535650/93918235-0b3f7680-fcda-11ea-915c-94716fd4ad15.png)

**Comment by pkhabazi** [comment]
hi @alphaomega0 can you share your JSON file so that I can take a better look

**Comment by pemontto** [comment]
@alphaomega0 it looks like your `query` field is unescaped. It has newlines characters in it which aren't valid JSON. The line starting `"query": "let starttime =14d;` should continue with escaped newlines characters `\n` instead of actual newlines.

**Comment by pkhabazi** [comment]
hi @alphaomega0 have you tried the feedback proposed by @pemontto? and can you please let us know if you need more help with this issue? kr Pouyan

**Comment by pkhabazi** [comment]
closing this issue, please feel free open a new issue if you are still having problem importing  Alert rules
